stretch_mujoco_driver:
  ros__parameters:
    use_mujoco_viewer: true
    mode: navigation
    use_robocasa: true
    robocasa_layout: G-shaped
    robocasa_style: Modern_1
    scene_package: stretch_simulation
    scene_file: coffee_scene
    use_cameras: false
    robocasa_task: PnPCounterToCab
    broadcast_odom_tf: true
    fail_out_of_range_goal: false
    robot_spawn_pose_pos: "3.0 -2.0 0.0"
    robot_spawn_pose_quat: "0.0 0.0 0.0 1.0"